export const TOGGLE_MENU = "TOGGLE_MENU";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const RESET_QUESTIONS = "RESET_QUESTIONS";
export const SHOW_WIN_AMOUNT = "SHOW_WIN_AMOUNT";
export const GET_CURRENT_QUESTION = "SHOW_WIN_AMOUNT";
export const TOGGLE_BUTTON = "TOGGLE_BUTTON";
